plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Yuvanesh KS Portfolio"
url: "https://north-abyss.github.io"
baseurl: "/Portfolio"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Forced settings to ensure proper serving
defaults:
  - scope:
      path: ""
    values:
      image: "https://north-abyss.github.io/Portfolio/preview.png"
